# Generated by Django 4.2.4 on 2023-08-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_test',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question_test',
            new_name='question_text',
        ),
    ]
